# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from home_monitoring_pkg/PredictionMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PredictionMsg(genpy.Message):
  _md5sum = "715dc63a1702758b9d710539c966074b"
  _type = "home_monitoring_pkg/PredictionMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string label_mask
string label_mask_prob
int64 x_start
int64 x_end
int64 y_start
int64 y_end
string label_pose
string label_pose_prob
float32 x_pose
float32 y_pose


"""
  __slots__ = ['label_mask','label_mask_prob','x_start','x_end','y_start','y_end','label_pose','label_pose_prob','x_pose','y_pose']
  _slot_types = ['string','string','int64','int64','int64','int64','string','string','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       label_mask,label_mask_prob,x_start,x_end,y_start,y_end,label_pose,label_pose_prob,x_pose,y_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PredictionMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.label_mask is None:
        self.label_mask = ''
      if self.label_mask_prob is None:
        self.label_mask_prob = ''
      if self.x_start is None:
        self.x_start = 0
      if self.x_end is None:
        self.x_end = 0
      if self.y_start is None:
        self.y_start = 0
      if self.y_end is None:
        self.y_end = 0
      if self.label_pose is None:
        self.label_pose = ''
      if self.label_pose_prob is None:
        self.label_pose_prob = ''
      if self.x_pose is None:
        self.x_pose = 0.
      if self.y_pose is None:
        self.y_pose = 0.
    else:
      self.label_mask = ''
      self.label_mask_prob = ''
      self.x_start = 0
      self.x_end = 0
      self.y_start = 0
      self.y_end = 0
      self.label_pose = ''
      self.label_pose_prob = ''
      self.x_pose = 0.
      self.y_pose = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.label_mask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.label_mask_prob
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4q().pack(_x.x_start, _x.x_end, _x.y_start, _x.y_end))
      _x = self.label_pose
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.label_pose_prob
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f().pack(_x.x_pose, _x.y_pose))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label_mask = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label_mask = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label_mask_prob = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label_mask_prob = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.x_start, _x.x_end, _x.y_start, _x.y_end,) = _get_struct_4q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label_pose = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label_pose = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label_pose_prob = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label_pose_prob = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.x_pose, _x.y_pose,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.label_mask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.label_mask_prob
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4q().pack(_x.x_start, _x.x_end, _x.y_start, _x.y_end))
      _x = self.label_pose
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.label_pose_prob
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f().pack(_x.x_pose, _x.y_pose))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label_mask = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label_mask = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label_mask_prob = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label_mask_prob = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.x_start, _x.x_end, _x.y_start, _x.y_end,) = _get_struct_4q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label_pose = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label_pose = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label_pose_prob = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label_pose_prob = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.x_pose, _x.y_pose,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_4q = None
def _get_struct_4q():
    global _struct_4q
    if _struct_4q is None:
        _struct_4q = struct.Struct("<4q")
    return _struct_4q
