blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
- -DPYTHON_EXECUTABLE=/home/mustar/anaconda3/envs/py36/bin/python3.6
- -DPYTHON_INCLUDE_DIR=/home/mustar/anaconda3/envs/py36/include/python3.6m
- -DPYTHON_LIBRARY=/home/mustar/anaconda3/envs/py36/lib/libpython3.6m.s
devel_layout: linked
devel_space: devel
extend_path: null
install: false
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
